# Change these first
owner: peaky-ai # Your GitHub organization or username, where this repository lives
repo: status-page # The name of this repository

sites:
  - name: Peaky Website (peaky.ai)
    url: https://peaky.ai
  - name: Peaky Platform (EU)
    url: https://eu.peaky.ai
  - name: Peaky Trust Center (trust.peaky.ai)
    url: https://trust.peaky.ai

assignees:
  - GuusDeGraeve

status-website:
  cname: status.peaky.ai
  name: Peaky Status
  themeUrl: https://status.peaky.ai/peaky-theme.css

i18n:
  footer: ''

user-agent: GuusDeGraeve