# Change these first
owner: peaky-ai # Your GitHub organization or username, where this repository lives
repo: status-page # The name of this repository

sites:
  - name: Peaky Website
    url: https://peaky.ai
  - name: Peaky Trust Center
    url: https://trust.peaky.ai

assignees:
  - GuusDeGraeve    

status-website:
  cname: status.peaky.ai
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Peaky Status