# Change these first
owner: peaky-ai # Your GitHub organization or username, where this repository lives
repo: status-page # The name of this repository

sites:
  - name: Peaky Website
    url: https://peaky.ai
  - name: Peaky Platform (EU)
    url: https://eu.peaky.ai
  - name: Peaky Trust Center
    url: https://trust.peaky.ai

assignees:
  - GuusDeGraeve

status-website:
  cname: status.peaky.ai
  name: ''
  logoUrl: https://status.peaky.ai/peaky-logo.svg
  themeUrl: https://status.peaky.ai/peaky-theme.css
  favicon: https://status.peaky.ai/peaky-icon.ico
  faviconSvg: https://status.peaky.ai/peaky-icon.svg
  navbar:
    - title: Go to Peaky
      href: https://peaky.ai
i18n:
  footer: ''

user-agent: GuusDeGraeve